platform :ios, '10.0'
use_frameworks!

target 'TWC iOS' do
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'XLPagerTabStrip'
  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'EzPopup'
  pod 'FittedSheets'
  #pod 'iOSDropDown'
  pod 'Toast-Swift'
  pod 'HSAttachmentPicker'
  pod 'JTAppleCalendar'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'DIKit'
  pod 'DropDown'
end
